name: Build Distributions

on: create

jobs:
  create-draft:
    name: Create Draft Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@v2
      - id: draft-release
        name: Draft Release
        uses: softprops/action-gh-release@v1

  build-distributions:
    name: Build Distributions
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@v2
      - id: setup-jdk
        name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - id: build
        name: Build distribution
        run: |
          gradle -v
          gradle build
      - id: upload-distributions
        name: Upload Distributions
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/distributions/*

  build-packages:
    name: Build System Packages on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          # - macos-latest
    steps:
      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@v2
      - id: setup-jdk
        name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - id: jpackage
        name: Run jpackage
        run: |
          gradle -v
          gradle jpackageDist
      - id: upload-distributions
        name: Upload Distributions
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/distributions/*
